version: '3.3'

services:
  api1: 
    container_name: api1
    build:
      context: ./SoftPlan.API1/
    ports:
      - "8081:80"

  api2:
    container_name: api2
    build:
      context: ./SoftPlan.API2/
    environment:
      URL_GITHUB: https://github.com/paulosjunior7/softplan-teste
      URL_API1: http://api1:8081/v1/taxajuros
    ports:
      - "8080:80"
    external_links:
      - api1
    links:
      - api1